name: Check Markdown

on:
  push:
  pull_request:
  schedule:
    - cron: '15 0,12 * * *'

jobs:
  markdown-link-check:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1

  markdownlint-cli2:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          command: config
          globs: |
            .github/workflows/.markdownlint.json
            **/*.md
